project:
  type: website

website:
  title: "Daniel Geiszler"
  favicon: favicon.png
  description: "This is Danny's personal blog."
  navbar:
    right:
      - text: CV
        href: DanielGeiszler_CV_20240425_A4.pdf
      - text: Blog
        href: blog.qmd

format:
  html:
    theme: cosmic
    css: styles.css



