project:
  type: website

website:
  title: "Daniel Geiszler"
  favicon: favicon.png
  description: "This is Danny's personal blog."
  navbar:
    left:
      - text: CV
        href: DanielGeiszler_CV_20241125_A4.pdf
      - text: Blog
        href: blog.qmd
      - text: Dashboards
        href: dashboards.qmd

    right:
      - icon: twitter
        href: https://x.com/GeiszlerDaniel
      - icon: linkedin
        href: https://www.linkedin.com/in/daniel-geiszler-868077a6/
      - icon: github
        href: https://github.com/danielgeiszler/
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=R-QRYkgAAAAJ&hl=en
  site-url: "https://danny.bio"
  repo-url: https://github.com/danielgeiszler/personalwebsite
  repo-actions: [source]
  page-footer:
    center: 
      - text: "© Daniel Geiszler 2024<br>danny.geisz@gmail.com"

format:
  html:
    theme: cosmic
    css: styles.css



