project:
  type: website

website:
  title: "Daniel Geiszler"
  description: "This is Danny's personal blog."
  navbar:
    right:
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmic
    css: styles.css



