project:
  type: website

website:
  title: "Daniel Geiszler"
  favicon: favicon.png
  description: "This is Danny's personal blog."
  navbar:
    right:
      - text: CV
        href: DanielGeiszler_CV_20240425_A4.pdf
      - text: Blog
        href: blog.qmd
  page-footer:
    left:
      - text: "© Daniel Geiszler 2024"
    center:
      - icon: twitter
        href: https://x.com/GeiszlerDaniel
      - icon: linkedin
        href: https://www.linkedin.com/in/daniel-geiszler-868077a6/
      - icon: github
        href: https://github.com/danielgeiszler/
      - icon: mortarboard-fill
        href: https://scholar.google.com/citations?user=R-QRYkgAAAAJ&hl=en

format:
  html:
    theme: cosmic
    css: styles.css



